server:
  port: 8082

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
      username: root
      password: xxx
      driver-class-name: com.mysql.cj.jdbc.Driver


